console.log("Halo, dunia! // Indonesian");
console.log("Ciao, mondo! // Italian");
console.log("Hola, mundo! // Spanish");
console.log("Γειά, σου Κόσμε // Griego");
console.log("Helló, Világ // Húngaro");
console.log("Привет, мир // Ruso");
console.log("Hej, Verden // Danés");
console.log("Selam, Dünya // Turco");
console.log("こんにちは世界 // Japonés");
console.log("Sawubona, Mhlaba // Zulú");
